spring:
  application:
    name: task-tracker-email-sender
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: emails
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fakechitor.*.producer.event"
        spring.json.type.mapping: |
          com.fakechitor.tasktrackerbackend.producer.event.UserRegistrationEvent:com.fakechitor.tasktrackeremailsender.dto.EmailMessage,
          com.fakechitor.tasktrackerscheduler.producer.event.ScheduleEvent:com.fakechitor.tasktrackeremailsender.dto.EmailMessage

server:
  port: 8091
resend:
  api: ${RESEND_API}
  email: ${RESEND_EMAIL}