spring:
  application:
    name: task-tracker-backend
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
security:
  jwt:
    secret_key: ${JWT_SECRET}
    access_token_expiration: 360000000
server:
  port: 8090