spring:
  application:
    name: task-tracker-scheduler
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
server:
  port: 8092